"""
    Yieldster SDK API

    Swagger documentation for Yieldster 2.0 SDK API's  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import PythonNew1.openapi_client
from PythonNew1.openapi_client.api.path_execution_service_api import PATHEXECUTIONSERVICEApi  # noqa: E501


class TestPATHEXECUTIONSERVICEApi(unittest.TestCase):
    """PATHEXECUTIONSERVICEApi unit test stubs"""

    def setUp(self):
        self.api = PATHEXECUTIONSERVICEApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_check_for_direct_paths(self):
        """Test case for check_for_direct_paths

        API to check whether direct path exist  # noqa: E501
        """
        pass

    def test_execute_strategy_path(self):
        """Test case for execute_strategy_path

        API to execute strategy path  # noqa: E501
        """
        pass

    def test_fetch_all_paths(self):
        """Test case for fetch_all_paths

        API to get all available execution paths  # noqa: E501
        """
        pass

    def test_fetch_direct_graph(self):
        """Test case for fetch_direct_graph

        API to get all direct paths from start token to end token without swapping into any intermediate tokens  # noqa: E501
        """
        pass

    def test_find_paths(self):
        """Test case for find_paths

        API to get paths that lead us from start token to end token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
