"""
    Yieldster SDK API

    Swagger documentation for Yieldster 2.0 SDK API's  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import PythonNew1.openapi_client
from PythonNew1.openapi_client.api.vault_service_api import VAULTSERVICEApi  # noqa: E501


class TestVAULTSERVICEApi(unittest.TestCase):
    """VAULTSERVICEApi unit test stubs"""

    def setUp(self):
        self.api = VAULTSERVICEApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_assign_advisor(self):
        """Test case for assign_advisor

        API to assign an advisor to a vault  # noqa: E501
        """
        pass

    def test_get_advisor_setting_by_vault_id(self):
        """Test case for get_advisor_setting_by_vault_id

        API to get vault Advisor settings of a vault  # noqa: E501
        """
        pass

    def test_get_asset_by_vault_id(self):
        """Test case for get_asset_by_vault_id

        API to get asset details of a vault  # noqa: E501
        """
        pass

    def test_get_invested_protocol_by_vault_id(self):
        """Test case for get_invested_protocol_by_vault_id

        API to get invested protocol of a vault  # noqa: E501
        """
        pass

    def test_get_protocols_by_vault_id(self):
        """Test case for get_protocols_by_vault_id

        API to get supported protocols of a vault  # noqa: E501
        """
        pass

    def test_get_vault_by_id(self):
        """Test case for get_vault_by_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
