"""
    Yieldster SDK API

    Swagger documentation for Yieldster 2.0 SDK API's  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import PythonNew1.openapi_client
from PythonNew1.openapi_client.api.add_asset_service_api import ADDASSETSERVICEApi  # noqa: E501


class TestADDASSETSERVICEApi(unittest.TestCase):
    """ADDASSETSERVICEApi unit test stubs"""

    def setUp(self):
        self.api = ADDASSETSERVICEApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_asset_list(self):
        """Test case for add_asset_list

        API to execute strategy path  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
